### ISSUE TITLE
Nuevo Issue de Ejemplo

### ISSUE THREAD

**Issue by brian101016** [BaLa-jak/git-act-final#7]
Acabo de revisar tu repositorio y los commits y las ramas las veo perfectamente.

Este mensaje es para confirmar tu acreditación del taller de GIT, enhorabuena :)

Veo que trabajaste con ramas separadas según la funcionalidad de la calculadora y que, a pesar de los múltiples merges y conflictos que pudieron surgir, lograste controlar la situación (desde VSC y GitHub con Pull Requests), e incluso miré que revertiste un PR y lo adaptaste posteriormente.

Muchas gracias por haber participado en el taller, este repositorio es prueba de que aprendiste algo nuevo y te invito a seguir experimentando con GitHub 👍 

(Marca este Issue como completado cuando leas este mensaje, te marqué como realizado individualmente)

**Comment by BaLa-jak** [comment]
Muchas gracias a ti y por todo el tiempo que estuviste con nosotros en el salon, yo creo que lo enseñaste de una manera en la que todos lo pudieran aprender
